# Generated by Django 6.0.8 on 2026-09-27 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beekeeper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "apiary_reg_no",
                    models.CharField(
                        max_length=40,
                        unique=True,
                        verbose_name="Apiary registration no.",
                    ),
                ),
                ("location", models.CharField(max_length=160)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("certified_organic", models.BooleanField(default=False)),
                ("joined_on", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "floral_source",
                    models.CharField(
                        help_text="Dominant nectar source, e.g. Mustard, Litchi, Multiflora",
                        max_length=120,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("installed_on", models.DateField(default=django.utils.timezone.now)),
                (
                    "beekeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hives",
                        to="core.beekeeper",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("honey_type", models.CharField(max_length=120)),
                ("harvest_date", models.DateField(default=django.utils.timezone.now)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("harvested", "Harvested"),
                            ("processing", "Processing"),
                            ("packaged", "Packaged"),
                            ("in_transit", "In transit"),
                            ("on_shelf", "On shelf"),
                            ("sold", "Sold"),
                        ],
                        default="harvested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="core.hive",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("genesis", "Chain created"),
                            ("harvest", "Harvested from hive"),
                            ("extraction", "Honey extracted"),
                            ("lab_test", "Quality / lab test"),
                            ("processing", "Processed & filtered"),
                            ("packaging", "Bottled & labelled"),
                            ("warehouse", "Stored in warehouse"),
                            ("transit", "Shipped to retailer"),
                            ("retail", "Received by retailer"),
                            ("sold", "Sold to consumer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        help_text="Who performed this step", max_length=160
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=160)),
                ("note", models.TextField(blank=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured metrics for this step",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("nonce", models.PositiveIntegerField(default=0)),
                ("previous_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="core.batch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "index"],
                "unique_together": {("batch", "index")},
            },
        ),
    ]
